Fix UI crash regarding exoplayer default
Fixes b8dbb3f07 "Use 64 KiB as the default progressive load interval"

java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer:
java.lang.NumberFormatException: For input string: "default"
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3226)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1586)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.Integer.parseInt(Integer.java:521)
	at java.lang.Integer.parseInt(Integer.java:556)
	at org.schabi.newpipe.player.helper.PlayerHelper.getProgressiveLoadIntervalBytes(PlayerHelper.java:434)
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:42)
	at org.schabi.newpipe.player.Player.<init>(Player.java:433)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:106)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3216)
	... 8 more